# Generated by Django 3.1.7 on 2021-12-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPropietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_propietario', models.IntegerField(blank=True, null=True)),
                ('nombre_propietario', models.TextField(blank=True, null=True)),
                ('email_propietario', models.TextField(blank=True, null=True)),
                ('usuario_propietario', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('telefono_propietario', models.TextField(blank=True, null=True)),
                ('last_login', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'USUARIO_PROPIETARIO',
                'managed': False,
            },
        ),
    ]
