# Generated by Django 3.1.7 on 2021-12-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_propietario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserPropietario',
        ),
    ]
